db:
  build: ./docker/postgres
#  image: hermes:5001/db
  hostname: db
  domainname: localdomain
  ports:
    - 15432:5432
  volumes: 
    - /srv/docker/ckan/db:/var/lib/postgresql/data

solr:
  build: ./docker/solr
#  image: hermes:5001/solr
  hostname: solr
  domainname: localdomain
  ports:
    - 18983:8983
  volumes:
   - /srv/docker/ckan/solr:/opt/solr/example/solr/ckan

datapusher:
  build: ./docker/datapusher
  hostname: datapusher
  domainname: localdomain

ckan:
  build: .
  hostname: ckan
  domainname: localdomain
  links:
    - db:db
    - solr:solr
    - datapusher:datapusher
  ports:
    - 80:80
  volumes:
    - /srv/docker/ckan/filestore:/srv/app/store
    - /srv/docker/ckan/conf:/srv/app/conf
    - /srv/docker/ckan/httpd:/var/log/httpd
